// app.js — home view + boot. MUST load LAST (after engines, nav, and all data/*.js).
// Runs at end of <body> so the DOM is ready. Stepper pages are generated by buildPages() from the PAGES registry.

  /* ---------- quiz: kalima types (home) ---------- */
  makeQuiz('quiz-home', {
    prompt: 'এই শব্দটি কোন প্রকার?',
    choices: [
      { type:'ism',  ar:'اِسْم', bn:'ইসম' },
      { type:'fil',  ar:'فِعْل', bn:"ফি'ল" },
      { type:'harf', ar:'حَرْف', bn:'হরফ' },
    ],
    words: [
      { ar:'كِتَاب',  type:'ism',  gloss:'বই',      why:'এটি একটি জিনিসের নাম, তাই ইসম। এর আগে <span class="ar">الْ</span> (আল-) লাগানো যায়।' },
      { ar:'كَتَبَ',  type:'fil',  gloss:'সে লিখলো', why:'অতীতকালের কাজ — কাজের সাথে সময় জড়িত, তাই ফি\'ল।' },
      { ar:'فِي',     type:'harf', gloss:'ভিতরে',    why:'একা বললে পূর্ণ অর্থ হয় না — অন্য শব্দের সাথে মিলে অর্থ দেয়, তাই হরফ।' },
      { ar:'مَسْجِد', type:'ism',  gloss:'মসজিদ',    why:'এটি একটি জায়গার নাম, তাই ইসম।' },
      { ar:'يَذْهَبُ', type:'fil', gloss:'সে যায়',   why:'বর্তমান/ভবিষ্যৎ কালের কাজ — সময় জড়িত, তাই ফি\'ল।' },
      { ar:'مِنْ',    type:'harf', gloss:'থেকে',     why:'নিজে অর্থ বহন করে না, সম্পর্ক বোঝায় — তাই হরফ।' },
      { ar:'وَلَد',   type:'ism',  gloss:'ছেলে',     why:'এটি মানুষের নাম, তাই ইসম। তানভীন (وَلَدٌ) আসতে পারে।' },
      { ar:'هَلْ',    type:'harf', gloss:'কি? (প্রশ্ন)', why:'প্রশ্নবোধক অব্যয় — একা অর্থহীন, বাক্যে অর্থ দেয়, তাই হরফ।' },
      { ar:'جَلَسَ',  type:'fil',  gloss:'সে বসলো',  why:'অতীতের কাজ — সময় আছে, তাই ফি\'ল।' },
      { ar:'بَيْت',   type:'ism',  gloss:'ঘর',       why:'একটি জিনিস/জায়গার নাম, তাই ইসম।' },
    ],
  });

  /* ---------- build all stepper pages from the PAGES registry ---------- */
  buildPages();

  /* ---------- home cards → top-level pages ---------- */
  ['ism','fil','harf'].forEach(t=>{
    const card = document.getElementById(`${t}-card`);
    card.addEventListener('click', ()=>show(t));
    card.addEventListener('keydown', e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); show(t); } });
  });

  show(null);   // start on home
